### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by GH05T-HUNTER5** [47hxl-53r/secure_cpp_banking#1]
The code uses -1 as an error indicator in the deposit and withdraw functions, which can be improved for better error reporting

**Comment by GH05T-HUNTER5** [comment]
We wish you the utmost success on your journey!

**Comment by 47hxl-53r** [comment]
> The code uses -1 as an error indicator in the deposit and withdraw functions, which can be improved for better error reporting

Thanks for pulling up this issue, How would you plan on improving the error indication rather than using -1. Any suggestions would be helpful

**Comment by GH05T-HUNTER5** [comment]
Invite me and I will help you fix this code

**Comment by 47hxl-53r** [comment]
Reporting the bug to https://t.me/ieatkidsforlunch would be a better option. Thankyou.

**Comment by GH05T-HUNTER5** [comment]
👋
